version: "3"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - fam/.env

  lookup_service:
    build: .
    command: >
      sh -c "python manage.py lookup_runserver"
    env_file:
      - fam/.env
